-- Script for dropping tables


DROP TABLE TAGS;
DROP TABLE ALBUMS CASCADE CONSTRAINT;
DROP TABLE PHOTOS CASCADE CONSTRAINT;
DROP TABLE PARTICIPANTS;
DROP TABLE USER_EVENTS;
DROP TABLE EDUCATION;
DROP TABLE PROGRAMS;
DROP TABLE MESSAGES;
DROP TABLE USER_HOMETOWN_CITIES;
DROP TABLE USER_CURRENT_CITIES;
DROP TABLE CITIES;
DROP TABLE FRIENDS;
DROP TABLE USERS;
DROP SEQUENCE INCREMENT_SEQ;

