CREATE VIEW StudentPairs AS
SELECT DISTINCT E1.SID AS SID1, E2.SID AS SID2
FROM Enrollments E1, Enrollments E2, Members M1, Members M2
WHERE E1.SID <> E2.SID AND E1.CID = E2.CID 
AND M1.SID = E1.SID AND M2.SID = E2.SID AND E1.SID < E2.SID
AND NOT EXISTS (
	SELECT P1.PID 
	FROM Members P1
	WHERE P1.SID = E1.SID
	INTERSECT
	SELECT P2.PID 
	FROM Members P2
	WHERE P2.SID = E2.SID
);