DROP TABLE Authors CASCADE CONSTRAINTS;
DROP TABLE Publishers CASCADE CONSTRAINTS;
DROP TABLE Books CASCADE CONSTRAINTS;
DROP TABLE Editions CASCADE CONSTRAINTS;
DROP TABLE Subjects CASCADE CONSTRAINTS;